package com.lavanya.escalade.service;

import java.util.List;
import java.util.Optional;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import com.lavanya.escalade.error.UserAlreadyExistException;
import com.lavanya.escalade.model.User;
import com.lavanya.escalade.repository.UserRepository;

@Service
public class UserService implements interfaceUserService, UserDetailsService{
	
	// This means to get the bean called userRepository
	//  Which is auto-generated by Spring, we will use it to handle the data
	@Autowired
	private UserRepository userRepository;
	
	@Autowired
	private PasswordEncoder passwordEncoder;
	
	public Page<User> getAllUsers(int pageNumber) {
		Sort sort = Sort.by("lastName").ascending();
		Pageable pageable = PageRequest.of(pageNumber -1, 10, sort);
		
		return userRepository.findAll(pageable);
	}
	
	@Transactional
    @Override
	public User save(final User user) throws UserAlreadyExistException{
		
		if (emailExists(user.getEmail())) {   
            throw new UserAlreadyExistException(
              "Il existe déjà un email avec l'addresse: "  
              + user.getEmail());
        }
		
		user.setEncodedPassword(passwordEncoder.encode(user.getPassword()));
		
		return userRepository.save(user);
	}
	
	private boolean emailExists(String email) {
		Optional<User> user = userRepository.findByEmail(email);
        return userRepository.findByEmail(email).isPresent();
    }
	
	
	public User getUserById(int id) {
		
		Optional<User>  userResponse = userRepository.findById(id);
		User user = userResponse.get();
		return user;
	}
	
	@Override
	public UserDetails loadUserByUsername(String email) throws UsernameNotFoundException {

		Optional<User> user = userRepository.findByEmail(email);

		user.orElseThrow(() -> new UsernameNotFoundException(email + " n'a pas été trouvé"));

		return user.map(MyUserDetails::new).get();
	}
	
	public Integer getTotalUsersRegistered() {
		
		return userRepository.countUsersRegistered();
	}

}
